import React from "react";
import "./About.css";

const TECH_STACK = [
  { icon: "⚛️",  label: "React 18" },
  { icon: "🪝",  label: "React Hooks" },
  { icon: "🔀",  label: "React Router v5" },
  { icon: "🌐",  label: "Fetch API" },
  { icon: "🎨",  label: "Vanilla CSS" },
  { icon: "📦",  label: "Create React App" },
  { icon: "🏛️", label: "Class Components" },
  { icon: "⚡",  label: "ES2020+" },
];

function About() {
  return (
    <div className="about-page">
      <div className="container">
        {/* Header */}
        <header className="about-header">
          <div className="about-header__eyebrow">
            <span className="badge badge-accent">ℹ️ About This Project</span>
          </div>
          <h1 className="about-header__title">
            About <span className="gradient-text">People Directory</span>
          </h1>
          <p className="about-header__subtitle">
            A React learning project showcasing modern component patterns, API
            integration, and dynamic UI updates.
          </p>
        </header>

        {/* Content cards */}
        <div className="about-grid">
          <article className="about-card">
            <span className="about-card__icon" aria-hidden="true">🎯</span>
            <h2 className="about-card__title">What is this?</h2>
            <p className="about-card__text">
              <strong style={{ color: "var(--color-text-primary)" }}>People Directory</strong> is
              a React application that fetches and displays randomly generated user profiles from the{" "}
              <a
                href="https://randomuser.me"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "#a5b4fc" }}
              >
                Random User API
              </a>
              . Users can explore profiles with details including name, location, email, and date of
              birth.
            </p>
            <p className="about-card__text">
              The app was built as a hands-on React learning exercise, demonstrating both functional
              components with hooks and class-based components side by side.
            </p>
          </article>

          <article className="about-card">
            <span className="about-card__icon" aria-hidden="true">🧠</span>
            <h2 className="about-card__title">What you'll learn</h2>
            <p className="about-card__text">
              This project covers core React concepts including component composition, state
              management with <code style={{ color: "#a5b4fc", fontFamily: "monospace" }}>useState</code>,
              side effects with{" "}
              <code style={{ color: "#a5b4fc", fontFamily: "monospace" }}>useEffect</code>, and
              lifecycle methods in class components.
            </p>
            <p className="about-card__text">
              It also demonstrates client-side routing with React Router, making API requests with
              the Fetch API, dynamic list rendering, and conditional UI states (loading, error,
              empty).
            </p>
          </article>
        </div>

        {/* Tech Stack */}
        <section className="about-tech" aria-labelledby="tech-heading">
          <h2 id="tech-heading" className="about-tech__title">
            <span aria-hidden="true">🛠️</span> Tech Stack
          </h2>
          <div className="about-tech__grid" role="list">
            {TECH_STACK.map((tech) => (
              <div key={tech.label} className="tech-chip" role="listitem">
                <span className="tech-chip__icon" aria-hidden="true">{tech.icon}</span>
                <span>{tech.label}</span>
              </div>
            ))}
          </div>
        </section>

        {/* API Attribution */}
        <aside className="about-attribution" aria-label="API Attribution">
          <span className="about-attribution__icon" aria-hidden="true">🌐</span>
          <div className="about-attribution__content">
            <h3 className="about-attribution__title">Powered by Random User API</h3>
            <p className="about-attribution__text">
              All user data is generated by{" "}
              <a
                href="https://randomuser.me"
                target="_blank"
                rel="noopener noreferrer"
                className="about-attribution__link"
              >
                randomuser.me
              </a>
              — a free, open-source API for generating random user data. No real personal
              information is used or stored.
            </p>
          </div>
        </aside>
      </div>
    </div>
  );
}

export default About;
